language: cpp
dist: trusty
sudo: required

install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - g++-7
    - libjack-jackd2-dev
    - libgles2-mesa-dev

compiler: gcc

script:
- cmake . -DCMAKE_BUILD_TYPE=Release
- make all
- bin/tests

# For pushing documentation
env:
  global:
  - ENCRYPTION_LABEL: "388c738922bf"
  - COMMIT_AUTHOR_EMAIL: "topisani@hamsterpoison.com"

notifications:
  email: false
